apiVersion: v1
kind: Service
metadata:
  name: metadata-svc-np
spec:
  type: NodePort
  selector:
    app: metadata-pod
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30003