apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-service-v2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: metadata-pod-v2
  template:
    metadata:
      labels:
        app: metadata-pod-v2
    spec:
      containers:
        - name: metadata-service-v2
          image: sunitparekh/metadata:v2.0
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 3
          env:
            - name: MONGODB_URI
              value: mongodb://mongo-service/metadata