apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-db-deploy
spec:
  selector:
    matchLabels:
      app: mongo-deploy
  template:
    metadata:
      labels:
        app: mongo-deploy
    spec: 
      containers:
        - name: mongo-db-deploy
          image: mongo
          ports:
            - containerPort: 27017